// Generated by skills/figma-spec-generator/scripts/build-figma-card-output.mjs
// Run this exact payload with the Figma MCP use_figma tool. Do not hand-roll frames.
// It creates canonical Case Template / One Complete Spec Block frames only.
const cardData = {
  "version": 3,
  "feature": "회원 태그",
  "generatedFrom": "case-inventory.json",
  "cards": [
    {
      "meta": {
        "platform": "Web",
        "user": "비즈",
        "screenName": "저장 및 반영",
        "screenPath": "회원 태그 / 저장 및 반영",
        "caseName": "저장 및 반영"
      },
      "descriptionBlocks": [
        {
          "marker": "P",
          "componentType": "Policy",
          "title": "회원 태그",
          "body": [
            "확정된 추가 서비스 정책 없음"
          ]
        },
        {
          "marker": "1",
          "componentType": "Section",
          "title": "저장 및 반영",
          "body": [
            "기능 관련 화면 영역을 표시한다."
          ]
        },
        {
          "marker": "2",
          "componentType": "Button",
          "title": "open Owner Detail",
          "body": [
            "사용자는 open Owner Detail, close Pet Sheet, submit Pet 동작을 실행할 수 있다.",
            "변경 내용을 저장한다.",
            "조건에 따라 관련 컨트롤의 활성 상태를 갱신한다."
          ]
        },
        {
          "marker": "3",
          "componentType": "State",
          "title": "상태 처리",
          "body": [
            "조건을 만족하지 않으면 관련 컨트롤을 비활성화한다.",
            "선택 상태를 화면에 반영한다.",
            "Keep the control disabled without tooltip unless the UX spec requires explanatory copy."
          ]
        },
        {
          "marker": "4",
          "componentType": "Value",
          "title": "데이터 반영",
          "body": [
            "저장 동작은 기능 데이터를 갱신한다.",
            "삭제 동작은 선택한 데이터를 제거한다.",
            "입력 변경은 화면의 임시 상태에 반영된다."
          ]
        },
        {
          "marker": "5",
          "componentType": "Toast",
          "title": "사용자 피드백",
          "body": [
            "Keep the current surface open and show an error toast."
          ]
        }
      ],
      "id": "S-03",
      "frameName": "3"
    },
    {
      "meta": {
        "platform": "App",
        "user": "비즈",
        "screenName": "저장 및 반영",
        "screenPath": "회원 태그 / 저장 및 반영",
        "caseName": "저장 및 반영"
      },
      "descriptionBlocks": [
        {
          "marker": "P",
          "componentType": "Policy",
          "title": "회원 태그",
          "body": [
            "확정된 추가 서비스 정책 없음"
          ]
        },
        {
          "marker": "1",
          "componentType": "Section",
          "title": "저장 및 반영",
          "body": [
            "기능 관련 화면 영역을 표시한다."
          ]
        },
        {
          "marker": "2",
          "componentType": "Option",
          "title": "open Owner Detail",
          "body": [
            "사용자는 open Owner Detail, close Pet Sheet, submit Pet 동작을 실행할 수 있다.",
            "변경 내용을 저장한다.",
            "선택한 항목을 삭제하거나 제거한다.",
            "조건에 따라 관련 컨트롤의 활성 상태를 갱신한다."
          ]
        },
        {
          "marker": "3",
          "componentType": "State",
          "title": "상태 처리",
          "body": [
            "조건을 만족하지 않으면 관련 컨트롤을 비활성화한다.",
            "선택 상태를 화면에 반영한다.",
            "Keep the control disabled without tooltip unless the UX spec requires explanatory copy."
          ]
        },
        {
          "marker": "4",
          "componentType": "Value",
          "title": "데이터 반영",
          "body": [
            "저장 동작은 기능 데이터를 갱신한다.",
            "삭제 동작은 선택한 데이터를 제거한다.",
            "입력 변경은 화면의 임시 상태에 반영된다."
          ]
        },
        {
          "marker": "5",
          "componentType": "Toast",
          "title": "사용자 피드백",
          "body": [
            "Keep the current surface open and show an error toast."
          ]
        }
      ],
      "id": "S-04",
      "frameName": "4"
    }
  ]
};
const figmaTemplate = {
  "source": "case-template-complete-spec-block",
  "fileKey": "FBR6bsRWFU99gd9HlWMF5h",
  "nodeId": "519:154",
  "templateComponentKey": "b2dcc7942b4bb1973bd43d4a8de0c889ac567ebf",
  "metaCaseComponentKey": "2aad9553334cb58f2e1e9cd08361490007516ae2",
  "descriptionTypeNodeId": "485:231",
  "descriptionTypeComponentSetKey": "46c1def11a0933e9c639b965b6427951a44bdbfd",
  "descriptionTypeComponentKeys": {
    "Policy": "e55f0cdd713d6ce59c45931aa9f4b117ebe8bbab",
    "Option": "ff12827ccec82d741cfed4f897e86f991410f21c",
    "Button": "45815d093b46c8281ee1899111a3e7e5cbd41694",
    "Toggle": "43676b0c6894be69271a10058492644f75d558f4",
    "Input": "eceb5677f00b006568c746c0c7d7cb7d82643f9c",
    "DatePicker": "1d0f6f76ab71c8d155514374aa79224d47eb2fa8",
    "Alert": "dc427fd733e5bd55eef08cb60ebed35d9e5ac516",
    "Toast": "031f98b10b92f0b19924ee9f343b0bc8ec89a73f",
    "Text": "1faf09f10b8c7b5fd728247f9b36991038f66b70",
    "Value": "9e76a5d50a6917a4297879d22e7ab5dcf0ee39c8",
    "Section": "fc5954433f41c5407df436526e095909cfd905d2",
    "State": "b984fbd14344dacb3c0c0973e4f3011a0f831ecc",
    "Navigation": "8d346fdb3182da3b9c2bfa2dd85b17d6b3d5165b",
    "List": "b5af3d320c3c9eb3a4df5a2a84600a1fcddc385f",
    "Card": "cf31b67946847508bb524cde952fb565d39b3f76"
  },
  "blockWidth": 2160,
  "blockHeight": 960,
  "screenWidth": 1280,
  "screenHeight": 960,
  "panelWidth": 840,
  "gap": 40,
  "numberMarkerSize": 36,
  "accent": "#9fc14f",
  "policyAccent": "#1e78f0",
  "injectionFormat": {
    "version": 1,
    "rules": [
      "Generation scripts must read this local format and must not infer text-node structure from Figma at runtime.",
      "If this format no longer matches the published component, sync this JSON first instead of adding guesses to generation scripts."
    ],
    "metaCase": {
      "componentName": "META / Case",
      "textNodeSequence": [
        {
          "role": "label",
          "label": "플랫폼"
        },
        {
          "role": "value",
          "key": "platform",
          "default": "Web"
        },
        {
          "role": "label",
          "label": "유저"
        },
        {
          "role": "value",
          "key": "user",
          "default": "비즈"
        },
        {
          "role": "label",
          "label": "화면명"
        },
        {
          "role": "value",
          "key": "screenName",
          "default": "-"
        },
        {
          "role": "label",
          "label": "화면 경로"
        },
        {
          "role": "value",
          "key": "screenPath",
          "default": "-"
        },
        {
          "role": "label",
          "label": "Case"
        },
        {
          "role": "value",
          "key": "caseName",
          "default": "-"
        }
      ]
    },
    "descriptionType": {
      "componentName": "Description Type",
      "textSlots": {
        "marker": {
          "textName": "Number",
          "index": 0,
          "sourceKey": "marker"
        },
        "title": {
          "textName": "Target",
          "index": 1,
          "sourceKey": "title"
        },
        "body": {
          "textName": "Details",
          "index": 2,
          "sourceKey": "body",
          "format": "bulletLines"
        }
      }
    }
  }
};
const figmaOutput = {
  "targetFileKey": "",
  "targetNodeId": "164:4377",
  "rootName": "SECTION / 회원 태그",
  "cardsPerSection": 10,
  "maxPayloadBytes": 18000,
  "replaceExisting": false,
  "payloadBatchNumber": 2,
  "payloadBatchTotal": 15,
  "payloadBatchFinal": false
};

const BLOCK_WIDTH = figmaTemplate.blockWidth;
const BLOCK_HEIGHT = figmaTemplate.blockHeight;
const PANEL_WIDTH = figmaTemplate.panelWidth;
const COMPLETE_SPEC_TEMPLATE = await importTemplateComponent();
const DESCRIPTION_COMPONENTS = await importDescriptionTypeComponents();

const target = await resolveTargetNode();
await prepareTargetPage(target);
if (figmaOutput.replaceExisting) removeExistingOutput(target);

const roots = [];
const batches = chunkCards(cardData.cards, figmaOutput.cardsPerSection || 10);
for (let index = 0; index < batches.length; index += 1) {
  const batch = batches[index];
  const root = createSectionRoot(batch, index, batches.length);
  target.appendChild(root);
  root.x = 0;
  root.y = index === 0 ? 0 : roots[index - 1].y + roots[index - 1].height + 240;
  for (const card of batch) {
    root.appendChild(await createCompleteSpecBlock(card));
  }
  roots.push(root);
}

if (!roots.length) throw new Error("No cards were available for Figma output.");
figma.viewport.scrollAndZoomIntoView(roots);
return {
  feature: cardData.feature,
  targetNodeId: figmaOutput.targetNodeId || "(current page)",
  rootName: figmaOutput.rootName,
  payloadBatchNumber: figmaOutput.payloadBatchNumber || 1,
  payloadBatchTotal: figmaOutput.payloadBatchTotal || 1,
  sections: roots.length,
  cards: cardData.cards.length,
  status: "created"
};

async function resolveTargetNode() {
  if (!figmaOutput.targetNodeId) return figma.currentPage;
  const node = typeof figma.getNodeByIdAsync === "function"
    ? await figma.getNodeByIdAsync(figmaOutput.targetNodeId)
    : figma.getNodeById(figmaOutput.targetNodeId);
  if (!node) throw new Error("Figma target node not found: " + figmaOutput.targetNodeId);
  if (!("appendChild" in node)) throw new Error("Figma target node cannot contain generated spec blocks: " + node.type);
  return node;
}

async function prepareTargetPage(targetNode) {
  const page = targetNode.type === "PAGE" ? targetNode : findAncestorPage(targetNode);
  if (page && figma.currentPage.id !== page.id) await figma.setCurrentPageAsync(page);
}

function findAncestorPage(node) {
  let current = node;
  while (current) {
    if (current.type === "PAGE") return current;
    current = current.parent;
  }
  return null;
}

function removeExistingOutput(targetNode) {
  const rootName = figmaOutput.rootName || ("SECTION / " + cardData.feature);
  const removable = [...targetNode.children].filter((child) => child.name === rootName || child.name.startsWith(rootName + " / "));
  for (const child of removable) child.remove();
}

function createSectionRoot(batch, index, total) {
  const root = figma.createFrame();
  const first = batch[0]?.frameName || String(index + 1);
  const last = batch[batch.length - 1]?.frameName || first;
  const batchPrefix = figmaOutput.payloadBatchTotal > 1
    ? " / " + String(figmaOutput.payloadBatchNumber).padStart(3, "0")
    : "";
  const rangeSuffix = total > 1 || figmaOutput.payloadBatchTotal > 1
    ? " / " + String(first).padStart(2, "0") + "-" + String(last).padStart(2, "0")
    : "";
  const suffix = batchPrefix + rangeSuffix;
  root.name = (figmaOutput.rootName || ("SECTION / " + cardData.feature)) + suffix;
  root.fills = [];
  root.layoutMode = "VERTICAL";
  root.primaryAxisSizingMode = "AUTO";
  root.counterAxisSizingMode = "AUTO";
  root.paddingLeft = 100;
  root.paddingRight = 100;
  root.paddingTop = 100;
  root.paddingBottom = 100;
  root.itemSpacing = 80;
  return root;
}

function chunkCards(cards, size) {
  const chunks = [];
  for (let index = 0; index < cards.length; index += size) {
    chunks.push(cards.slice(index, index + size));
  }
  return chunks;
}

async function createCompleteSpecBlock(card) {
  const templateBlock = await createTemplateBlock(card);
  if (templateBlock) return templateBlock;

  throw new Error("Case Template / One Complete Spec Block component import failed. Sync the Figma template contract before generation.");
}

async function importTemplateComponent() {
  try {
    return await figma.importComponentByKeyAsync(figmaTemplate.templateComponentKey);
  } catch (error) {
    return null;
  }
}

async function createTemplateBlock(card) {
  if (!COMPLETE_SPEC_TEMPLATE) return null;
  const instance = COMPLETE_SPEC_TEMPLATE.createInstance();
  instance.name = "Case Template / One Complete Spec Block / " + card.frameName;
  instance.resize(BLOCK_WIDTH, BLOCK_HEIGHT);
  const block = instance.detachInstance();
  block.name = "Case Template / One Complete Spec Block / " + card.frameName;

  const screen = block.findOne((node) => node.name === "Screen" && node.type === "FRAME");
  if (screen && "children" in screen) {
    for (const child of [...screen.children]) {
      if (child.type === "TEXT" && child.name === "Placeholder") child.remove();
    }
  }

  const metaName = figmaTemplate.injectionFormat.metaCase.componentName;
  const meta = block.findOne((node) => node.name === metaName && node.type === "INSTANCE");
  if (!meta) throw new Error("Template block is missing META / Case instance.");
  await applyMetaCaseValues(meta, card);

  const description = block.findOne((node) => node.name === "Spec Description" && node.type === "FRAME");
  if (!description) throw new Error("Template block is missing Spec Description frame.");
  for (const child of [...description.children]) child.remove();
  for (const item of card.descriptionBlocks) description.appendChild(await createDescription(item));

  return block;
}

async function applyMetaCaseValues(instance, card) {
  const sequence = figmaTemplate.injectionFormat.metaCase.textNodeSequence;
  const textNodes = instance.findAll((node) => node.type === "TEXT");
  if (textNodes.length < sequence.length) {
    throw new Error(`META / Case text count mismatch. Contract expects ${sequence.length}, instance has ${textNodes.length}.`);
  }

  for (let index = 0; index < sequence.length; index += 1) {
    const slot = sequence[index];
    const textNode = textNodes[index];
    if (slot.role === "label") {
      if (textNode.characters.trim() !== slot.label) {
        throw new Error(`META / Case label mismatch at text index ${index}. Expected "${slot.label}", found "${textNode.characters}". Sync contracts/figma/figma-spec-template-structure.json before generation.`);
      }
      continue;
    }
    if (slot.role !== "value") continue;
    await loadTextNodeFont(textNode);
    textNode.characters = card.meta?.[slot.key] || slot.default || "-";
  }
}

async function createDescription(item) {
  const instance = await createDescriptionTypeInstance(item);
  if (instance) return instance;
  throw new Error("Description Type component import failed for " + item.componentType + ". Sync the Figma template contract before generation.");
}

async function importDescriptionTypeComponents() {
  const map = new Map();
  const componentKeys = figmaTemplate.descriptionTypeComponentKeys || {};
  for (const [type, key] of Object.entries(componentKeys)) {
    try {
      const component = await figma.importComponentByKeyAsync(key);
      map.set(type, component);
    } catch (error) {
      // Validation fails later if any required Description Type component cannot be imported.
    }
  }

  const components = figma.root.findAll((node) => node.type === "COMPONENT");
  for (const component of components) {
    const type = component.name.match(/(?:속성 1|Property 1)\s*=\s*(Policy|Option|Button|Toggle|Input|DatePicker|Alert|Toast|Text|Value|Section|State|Navigation|List|Card)/)?.[1];
    if (type && !map.has(type)) map.set(type, component);
  }
  return map;
}

async function createDescriptionTypeInstance(item) {
  const component = DESCRIPTION_COMPONENTS.get(item.componentType);
  if (!component) return null;

  const instance = component.createInstance();
  instance.name = figmaTemplate.injectionFormat.descriptionType.componentName;
  instance.resize(PANEL_WIDTH, instance.height);

  const slots = figmaTemplate.injectionFormat.descriptionType.textSlots;
  const textNodes = instance.findAll((node) => node.type === "TEXT");
  const marker = findTextSlot(textNodes, slots.marker);
  const title = findTextSlot(textNodes, slots.title);
  const body = findTextSlot(textNodes, slots.body);
  if (!marker || !title || !body) {
    throw new Error("Description Type text slot mismatch for " + item.componentType + ". Sync the Figma template contract before generation.");
  }

  await loadTextNodeFont(marker);
  marker.characters = String(item.marker || "");
  await loadTextNodeFont(title);
  title.characters = item.componentType === "Policy" ? item.title || "정책명" : item.title || item.componentType;
  await loadTextNodeFont(body);
  body.characters = (item.body || []).map((bullet) => "• " + bullet).join("\n");

  return instance;
}

function findTextSlot(textNodes, slot) {
  if (!slot) return null;
  const byName = textNodes.find((node) => node.name === slot.textName);
  if (byName) return byName;
  if (Number.isInteger(slot.index)) return textNodes[slot.index] || null;
  return null;
}

async function loadTextNodeFont(node) {
  if (node.fontName === figma.mixed) {
    const first = node.getRangeFontName(0, 1);
    if (first !== figma.mixed) await figma.loadFontAsync(first);
    return;
  }
  await figma.loadFontAsync(node.fontName);
}

